### ISSUE TITLE
We cannot preview drafts in WP

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#114]
There are instances where we'd want to preview a draft before hitting publish. That's currently not possible. 
eg: https://cms.librestream.com/?p=13920&preview=true

**Comment by paulstroot** [comment]
@samyue888 and @tom - There was an issue that was causing an error when building the previews that I fixed with my recent update to development. I'm not quite sure how to test this though since the WordPress CMS references the live codebase for the previews. I'll do a little more experimenting in the morning. If that pending pull request for other issues gets merged in the meantime we can test the previews on the live site then.

**Comment by samyue888** [comment]
@paulstroot After merging, we still cannot preview drafts. eg: https://cms.librestream.com/?p=13920&preview=true
https://cms.librestream.com/wp-admin/post.php?post=13920&action=edit

**Comment by paulstroot** [comment]
Thanks. I'll keep investigating. The good news is that previews are successfully being built, so we have made some progress!

**Comment by samyue888** [comment]
It seems like we cannot preview published pages either. eg: https://cms.librestream.com/events/panasonic-tough-talks-webinar-the-workforce-of-the-future-with-librestream-technologies/?preview_id=13999&preview_nonce=5d2678d883&preview=true

**Comment by paulstroot** [comment]
Yea, It looks like the error is happening for all previews. I'll be taking
a deeper look into this tomorrow. THe previews are being built properly,
but for some reason the wordPress "loading preview" page isn't detecting
when the build finishes and displaying it. I'll keep you posted as I figure
out more.

**Comment by paulstroot** [comment]
@samyue888 - I'm looping in Gatsby Cloud support on this. Seems like there is a new issue since last night with the preview builds, so I'm asking them about that one first. This is a copy of my support request to them:

HI. We are having a couple issues with our GatsbyJS Preview builds. When we trigger a build, the build seems to get stuck on "Queued since ...". The build details say "Waiting for logs...". No other errors are being reported. We've waited hours and the build never starts. Are you able to see what is keeping these builds from being started?
Thank you!

**Comment by paulstroot** [comment]
Latest update from Grayson at Gatsby Cloud. I communicated with him a few times and gave him WordPress Access to our staging site to do some testing. He will help us troubleshoot this some more starting Monday, May 17th.

**Comment by paulstroot** [comment]
Latest update. I set up a minimal reproduction of both the gatsby site and the WordPress CMS and I'm still seeing the issue. I sent all of this info over to Grayson at Gatsby Cloud for help troubleshooting.

**Comment by samyue888** [comment]
@paulstroot Any updates on this?

**Comment by paulstroot** [comment]
Still working with Gatsby Cloud. I got a response earlier today saying that
they were still looking into it.


" We are still investigating, and I may reach back out for more
information, thanks!

Grayson Hicks

Senior Software Engineer, Customer Success"

**Comment by paulstroot** [comment]
**This should now be working!!**

I worked with customer support at Gatsby cloud and finally pinpointed the issue to a bug with the gatsby-source-wordrpess plugin, which we upgraded, and the need to also upgrade the WP Gatsby plug-in in the CMS.

I noticed that the preview does sometimes take a while to load, especially the first time, but then loads significantly faster on subsequent previews. It does involves some wait time for the page to build though each time you click "preview".

Also worth noting, the previews are victim to our persistent image caching problem (#119) like the rest of the pages, so if you update an image, you may need to preview a couple times before it works.

**Comment by samyue888** [comment]
Hi Paul. I'm still seeing this. I tried refreshing.
![image](https://user-images.githubusercontent.com/81642726/121091189-7b295a80-c79e-11eb-8e17-b0b662c67cde.png)

**Comment by paulstroot** [comment]
I had to click "preview" twice, but then it showed up okay for me. (fyi, a
"refresh" of the page will not work, you need to click "preview" again)

I have noticed that it sometimes doesn't work, and I need to click
"preview" again, which is a little bit frustrating. I tested it a couple
dozen times and only had about 50/50 success. I'm guessing that part of the
issue might be because our build times are so long, which is mainly because
we are downloading all static assets like documents and PDFs instead of
serving them from a content delivery network. I'll investigate a little bit
more this week and see what I can figure out.

**Comment by paulstroot** [comment]
@samyue888 - I believe this may be connected to our issue #119 with the images folder being moved away from the default location of "wp_content"

I tried building a preview in dozens of situations and I continually kept getting the error where the preview is built successfully in Gatsby Cloud, but the WordPres preview continues hanging on "Loading Preview". I finally got it to work consistently when I created a copy of the site and moved the media folder back into the default "wp-content" folder instead of "media". I think our best approach is to hold off on this issue until the image issue is fixed, and then re-visit.

In the meantime, because we now have a staging site and a live site, it should be easy to just publish your changes as you work on them and view on the staging site. The Staging site essentially is a preview because the changes are not pushed live until you click "deploy to live"

FYI, Tom and I are putting together an argument for using a CDN to deliver videos and documents that should increase performance and allow us to move the WordPress media folder back to default with minimal impact to the URLs. Stay tuned for that.

CC: @tbeck

**Comment by samyue888** [comment]
@paulstroot @tbeck Following up on this. Have we heard from Gatsby support?

**Comment by tbeck** [comment]
@samyue888 - There is no new information from Gatsby support.

If the root of the issue is that we are not using the default WP folders and you have already taken the steps to remove downloadable and streamable assets (video/pdf). Is there any reason that you don't want to utilize the default wp folder structure and move the remaining files out of the "media" folder? I was assuming that it was a vanity issue and that you did not want any reference to wordpress in your file paths?

**Comment by paulstroot** [comment]
I have had a couple scheduled meetings with Gatsby support to discuss this, but they have had to reschedule the meetings do to scheduling conflicts on their end each time, and then I left on vacation. I believe they were going to reach out to @tbeck  while I was away but I don't think he has heard from them about anything yet.

**Comment by samyue888** [comment]
@tbeck Yes, we would not want 'wp-content/uploads' in the url, which is not best practice.

@paulstroot Please update us once you've booked a call, thanks. It has been almost 2 months so we'd like to resolve this asap.

**Comment by paulstroot** [comment]
I just met with Shane from the Gatsby Cloud team. They are now aware of the issue and will be investigating this week. He hopes to get some info for me by Monday.

One thing to note, when on the call with him, I had a difficult time recreating the issue. Perhaps moving all of the videos to an external CMS was a big help here. I had suspected that maybe the size of the media on the site was causing issues. Try running a preview the next time you make changes and see if you have more success with it. (I did recreate the preview error about 20% of the time on my tests, so it's still not completely fixed)

Also of note, the Gatsby Cloud team is working on a pretty big update to this preview functionality they they hope to put out in about three weeks, so that could be a big help. I think now we just wait for some feedback from them.

cc @samyue888 and @tbeck

**Comment by tbeck** [comment]
Thanks @paulstroot!

**Comment by samyue888** [comment]
Thanks Paul. Here's a screenshot of what we're seeing:
eg: https://cms.librestream.com/?post_type=librestream_case&p=10840&preview=true
![image](https://user-images.githubusercontent.com/81642726/125676231-7f0f4edd-c3b3-4686-8b0e-ebe93aed4ab6.png)

**Comment by paulstroot** [comment]
I communicated with Grayson at Gatsby Cloud. He told me that the new preview infrastructure has been implemented on their end. I tested the preview functionality on the site and it is still not working, but this time I'm seeing NO_PREVIEW_PATH_FOUND error in the console. I replied to Greyson about this and hopefully will get a helpful response.

![image](https://user-images.githubusercontent.com/52838369/131513524-0987f742-dec7-4655-88d1-0d33be8ade85.png)
