### ISSUE TITLE
Change captcha to V2

### ISSUE THREAD

**Issue by paulstroot** [ocupop/librestream#125]
@samyue888 - I changed the google recaptcha on the Contact Support page to the style that shows a checkbox for the user to check.

I have set this up on a new development branch here:
https://librestreamdevelopcaptcha.gatsbyjs.io/contact-us-support/

But.. this domain is not on the list of approved domains for on the recaptcha account. **Can you please add *.gatsbyjs.io to the list? Once you do that it should work.** Please review and test once it is working.

We need to do some test submissions to make sure the data properly gets submitted to SalesForce. Once we know it's working I can make the changes to the development site and the live CMS page.

**Comment by samyue888** [comment]
@paulstroot Here are the list of domains (haven't changed since last time). Are we missing any?
![image](https://user-images.githubusercontent.com/81642726/118894112-79175e80-b8b8-11eb-8506-80efb9f2b7eb.png)

**Comment by samyue888** [comment]
I've added https://librestreamdevelopcaptcha.gatsbyjs.io and confirmed with a test submission that it is sending to SF successfully

**Comment by paulstroot** [comment]
Great! Should I go ahead and merge this into the develop branch so it can
be added to the pull request I just created?

**Comment by samyue888** [comment]
Yes please, thanks!

**Comment by paulstroot** [comment]
@samyue888 - I merged this branch into the develop branch, so it will get pushed to live with the next pull request.
I have created a new page for testing on the development site https://librestreamdevelop.gatsbyjs.io/contact-us-support-2/

When we go live, the captcha should then work at https://librestream.com/contact-us-support-2/. When that happens please let me know and I will copy the code form this test page over to the live Contact Support page in the CMS, and remove that testing page.

**Comment by samyue888** [comment]
The PR was merged, but the V2 checkbox doesn't show up:
https://librestream.com/contact-us-support/
![image](https://user-images.githubusercontent.com/81642726/119390880-82227a00-bc82-11eb-8868-e7d7fb55182e.png)

**Comment by samyue888** [comment]
@paulstroot We are still getting a lot of spam (12 in 12 hours):
![image](https://user-images.githubusercontent.com/81642726/119706627-14f01f80-be0f-11eb-8996-e4a82e1be906.png)

Would it be possible to force a puzzle every time for the V2?

Also, I noticed this message in the recaptcha page: "We detected that your site is not verifying reCAPTCHA solutions"
![image](https://user-images.githubusercontent.com/81642726/119706785-44069100-be0f-11eb-8614-9132caf3a8cc.png)
Which takes me to this link:
https://developers.google.com/recaptcha/docs/verify#api-request

**Comment by paulstroot** [comment]
Okay. I've put it on my list to investigate further.

**Comment by paulstroot** [comment]
@samyue888 - At this point I feel like the form HTML that liz provided to me does not work with SalesForce, so we would probably need to either get access to the SalesForce account to investigate some of the configuration options, or work with SalesForce technical support. Can we discuss this in our next meeting?

**Comment by samyue888** [comment]
Sure, let's discuss in tomorrow's meeting
