### ISSUE TITLE
Subheadings aren't clickable in ABOUT page

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#87]
https://librestream.com/about/

They were working previously. Perhaps related to some subheading changes made today?

**Comment by paulstroot** [comment]
This should be working properly now. They are anchor links to sections further down on the page.
@samyue888 please review.

**Comment by samyue888** [comment]
@paulstroot Just checked in incognito and they are still not clickable
![image](https://user-images.githubusercontent.com/81642726/115450047-494d3c00-a1d0-11eb-88db-b69ccf93eae5.png)

**Comment by paulstroot** [comment]
Sorry @samyue888. Forgot to paste a link to the development url where this is staged.
https://librestreamdevelop.gatsbyjs.io/about

**Comment by samyue888** [comment]
@paulstroot This develop link works. Thanks
